all:
# Example written in C
	make -C ./C/cexample1
# Example written in Fortran90
	make -C ./F90/test1
	make -C ./F90/test2
	make -C ./F90/test3
	make -C ./F90/test4
	make -C ./F90/test5
# Example written in C++ using ISO-C-Binding
	make -C ./isoC-matthias
# Example written in C using ISO-C-Binding
	make -C ./isoC-Teslos

clean:
	make -C ./C/cexample1 clean
	make -C ./F90/test1 clean
	make -C ./F90/test2 clean
	make -C ./F90/test3 clean
	make -C ./F90/test4 clean
	make -C ./F90/test5 clean
	make -C ./isoC-matthias clean
	make -C ./isoC-Teslos clean
