.PHONY : all clean

all:
	#make -C C/cexample1
	#make -C F90/test1
	#make -C F90/test2
	#make -C F90/test3
	make -C Cpp/cppexample1

clean:
	rm -f *.o *.mod
	#make -C C/cexample1 clean
	#make -C F90/test1 clean
	#make -C F90/test2 clean
	#make -C F90/test3 clean
	make -C Cpp/cppexample1 clean
