name: Build and Release OC6P

on:
  push:
    branches:
      - github-actions
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Linux and Windows runners

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Build for Linux (Ubuntu)
      - name: Build on Linux
        if: runner.os == 'Linux'
        steps:
          - name: Install CMake
            uses: jwlawson/actions-setup-cmake@v1
            with:
              cmake-version: '3.25.0'

          - name: Install GCC, G++, and GFortran
            run: |
              sudo apt-get update
              sudo apt-get install -y build-essential gfortran

          - name: Build with CMake
            run: |
              mkdir build
              cd build
              cmake ../
              make -j$(nproc)

          - name: Prepare Linux Artifact
            run: |
              mkdir -p artifacts
              cp build/bin/oc6p artifacts/

          - name: Upload Linux Build Artifact
            uses: actions/upload-artifact@v3
            with:
              name: oc6p-linux
              path: artifacts/oc6p

      # Build for Windows (MSYS2 with Ninja)
      - name: Install MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gfortran
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja

      - name: Add MSYS2 to Path
        if: runner.os == 'Windows'
        run: |
          echo "C:/msys64/usr/bin" >> $GITHUB_PATH
          echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH

      - name: Build with CMake and Ninja (MSYS2)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" ../
          ninja -j$(nproc)

      - name: Prepare Windows Artifact
        if: runner.os == 'Windows'
        run: |
          mkdir -p artifacts
          cp build/bin/oc6p.exe artifacts/

      - name: Upload Windows Build Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: oc6p-windows
          path: artifacts/oc6p.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print GitHub Ref
        run: echo "GITHUB REF: ${{ github.ref }}"

      - name: Download Linux Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: oc6p-linux
          path: artifacts/linux

      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: oc6p-windows
          path: artifacts/windows

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/oc6p
          asset_name: oc6p-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/oc6p.exe
          asset_name: oc6p-windows
          asset_content_type: application/octet-stream
