name: Build and Release OC6P with MSYS2

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - github-actions
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up MSYS2
        run: |
          echo "::set-output name=MSYS2_ROOT::$(cygpath -u "C:\\msys64")"
          choco install msys2 --version 20220524.0.0

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain

      - name: Create build directory
        run: mkdir build

      - name: Configure project
        run: |
          C:\msys64\mingw64\bin\cmake.exe -B build -S .

      - name: Build project
        run: |
          C:\msys64\mingw64\bin\cmake.exe --build build --config Release

      - name: Upload build artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: oc6p
          path: build/oc6p  # Updated path for the oc6p binary

  release:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up MSYS2
        run: |
          echo "::set-output name=MSYS2_ROOT::$(cygpath -u "C:\\msys64")"
          choco install msys2 --version 20220524.0.0

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-toolchain

      - name: Create build directory
        run: mkdir build

      - name: Configure project
        run: |
          C:\msys64\mingw64\bin\cmake.exe -B build -S .

      - name: Build project
        run: |
          C:\msys64\mingw64\bin\cmake.exe --build build --config Release

      - name: Package release
        run: |
          mkdir -p release
          cp build/oc6p release/
          tar -czf oc6p.tar.gz -C release .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./oc6p.tar.gz
          asset_name: oc6p.tar.gz
          asset_content_type: application/gzip
